"""add user role

Revision ID: dbeaf5b16630
Revises: 
Create Date: 2026-09-12 19:18:15.321757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbeaf5b16630'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(length=50),
            nullable=True
        )
    )

    op.execute(
        "UPDATE users SET role = 'USER' WHERE role IS NULL"
    )

    op.alter_column(
        'users',
        'role',
        existing_type=sa.String(length=50),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
